export { default as Course } from './Course';
export { default as UserGroup } from './UserGroup';
export { default as UserMultiple } from './UserMultiple';
export { default as Book} from './Book';
export { default as Calendar } from './Calendar';
export { default as DashboardSquare } from './DashboardSquare';
export { default as Students } from './Students';
export { default as Add } from './Add';
export { default as AddTeam } from './AddTeam';
export { default as Phone } from './Phone';
export { default as Video } from './Video';
export { default as Search } from './Search';
export { default as MoreHorizontal } from './MoreHorizontal';
export { default as Paperclip } from './Paperclip';
export { default as Mic } from './Mic';
export { default as Send } from './Send';
export { default as ArrowLeft } from './ArrowLeft';
